title: "49thIT"
author: "49thIT, LLC"
description: "An Alaskan serial adventure in IT..."

# Use only local theme files youâ€™ve vendored into the repo
theme: null

# Optional: nicer URLs and correct base path
permalink: /:title/
url: "https://49thit.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed

theme_config:
  show_copyright: true


